apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-explorer-backend
  name: web-explorer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-explorer-backend
  template:
    metadata:
      labels:
        app: web-explorer-backend
    spec:
      containers:
        - name: web-explorer-backend
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_STORAGE_URI
              value: redis://redis:6379/0
            - name: MONGODB_DATABASE
              value: web-explorer
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_S3_ENDPOINT
              value: https://static.totem-explorer.com
            - name: AWS_S3_BUCKET
              value: totem-web-explorer
            - name: PROVIDER_RPC
              value: https://matic-mumbai.chainstacklabs.com
            - name: ASSETS_AVATAR_CONTRACT
              value: 0xEE7ff88E92F2207dBC19d89C1C9eD3F385513b35
            - name: ASSETS_ITEM_CONTRACT
              value: 0xfC5654489b23379ebE98BaF37ae7017130B45086
            - name: ASSETS_GEM_CONTRACT
              value: 0x0e2a085063e15FEce084801C6806F3aE7eaDfBf5
          envFrom:
            - secretRef:
                name: web-explorer-backend
          image: 667950714614.dkr.ecr.us-east-1.amazonaws.com/web-explorer-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
