# Default values for kor-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-2.amazonaws.com/web-explorer-backend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "prod"

fullnameOverride: "web-explorer-backend"

containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/success-codes: '404'
    alb.ingress.kubernetes.io/group.name: main
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:667950714614:certificate/302a21b6-52db-4471-a6e5-b530540345a0
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: api.totem-explorer.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: web-explorer-backend
            servicePort: 80
  tls: []

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownSeconds: 3

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "third"
    effect: "NoSchedule"

env:
  ENV: ""


